server:
  port: 3344
spring:
  application:
    name: cloud-config-center1
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/fuhao6192/springcloud-config.git
          search-paths:
            - springcloud-config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
